// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"
	"net/http"

	"github.com/ixugo/ffagent/agent/internal/conf"
	"github.com/ixugo/ffagent/agent/internal/core/metadata/metadataapi"
	"github.com/ixugo/ffagent/agent/internal/data"
	"github.com/ixugo/ffagent/agent/internal/web/api"
	"github.com/ixugo/goddd/domain/version/versionapi"
)

// Injectors from wire.go:

func WireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	client := api.NewAIClient()
	executor := api.NewFFmpegExecutor(bc)
	metadataCore := metadataapi.NewMetadataCore(db)
	metadataAPI := metadataapi.NewMetadataAPI(metadataCore)
	uniqueidCore := api.NewUniqueID(db)
	chatCore := api.NewChatCore(db, uniqueidCore)
	chatAPI := api.NewChatAPI(chatCore)
	usecase := &api.Usecase{
		Conf:        bc,
		DB:          db,
		Version:     versionapiAPI,
		AIClient:    client,
		FFmpegExec:  executor,
		MetadataAPI: metadataAPI,
		ChatAPI:     chatAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
	}, nil
}
