// Code generated by godddx, DO AVOID EDIT.
package chat

import "github.com/ixugo/goddd/domain/uniqueid"

// Storer data persistence
type Storer interface {
	Session() SessionStorer
	Message() MessageStorer
}

// Core business domain
type Core struct {
	store Storer
	uni   uniqueid.Core
}

// NewCore create business domain
func NewCore(store Storer, uni uniqueid.Core) Core {
	return Core{store: store, uni: uni}
}
