// Code generated by godddx, DO AVOID EDIT.
package chat

import "time"

// Message domain model
type Message struct {
	ID          string    `gorm:"primaryKey" json:"id"`
	SessionID   string    `gorm:"column:session_id;notNull;default:''" json:"session_id"`
	Role        string    `gorm:"column:role;notNull;default:''" json:"role"`
	Content     string    `gorm:"column:content;notNull;default:''" json:"content"`
	Attachments string    `gorm:"column:attachments;notNull;default:''" json:"attachments"`
	CreatedAt   time.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName database table name
func (*Message) TableName() string {
	return "messages"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
// 默认应该是 ID 字段，但也可以自定义
func (m *Message) CacheKey() string {
	return m.ID
}
