// Code generated by godddx, DO AVOID EDIT.
package chat

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// MessageStorer Instantiation interface
type MessageStorer interface {
	Find(context.Context, *[]*Message, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Message, ...orm.QueryOption) error
	Add(context.Context, *Message) error
	Edit(context.Context, *Message, func(*Message), ...orm.QueryOption) error
	Del(context.Context, *Message, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	EditWithSession(*gorm.DB, *Message, func(b *Message) error, ...orm.QueryOption) error
}

// FindMessage Paginated search
func (c Core) FindMessages(ctx context.Context, in *FindMessageInput) ([]*Message, int64, error) {
	// Find 的 Pager 入参不会自动把 SessionID 转成 WHERE，必须显式加上 session_id 条件，否则侧栏切换会话时始终拉到全表消息
	if in.SessionID == "" {
		return []*Message{}, 0, nil
	}
	q := orm.NewQuery(2).
		Where("session_id = ?", in.SessionID).
		OrderBy("created_at ASC")

	items := make([]*Message, 0, in.Limit())
	total, err := c.store.Message().Find(ctx, &items, in, q.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetMessage Query a single object
func (c Core) GetMessage(ctx context.Context, id string) (*Message, error) {
	// 提前赋值是为了缓存
	out := Message{ID: id}
	if err := c.store.Message().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// AddMessage Insert into database
func (c Core) AddMessage(ctx context.Context, in *AddMessageInput) (*Message, error) {
	var out Message
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	// TODO: 建议定义前缀
	out.ID = c.uni.UniqueID("")
	if err := c.store.Message().Add(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// EditMessage Update object information
func (c Core) EditMessage(ctx context.Context, in *EditMessageInput, id string) (*Message, error) {
	var out Message
	if err := c.store.Message().Edit(ctx, &out, func(b *Message) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Edit id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DelMessage Delete object
func (c Core) DelMessage(ctx context.Context, id string) (*Message, error) {
	var out Message
	if err := c.store.Message().Del(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}
