// Code generated by godddx, DO AVOID EDIT.
package chat

import "github.com/ixugo/goddd/pkg/web"

type FindMessageInput struct {
	web.PagerFilter
	SessionID   string `form:"session_id"`
	Role        string `form:"role"`
	Content     string `form:"content"`
	Attachments string `form:"attachments"`
}

type EditMessageInput struct {
	SessionID   string `json:"session_id"`
	Role        string `json:"role"`
	Content     string `json:"content"`
	Attachments string `json:"attachments"`
}

type AddMessageInput struct {
	SessionID   string `json:"session_id"`
	Role        string `json:"role"`
	Content     string `json:"content"`
	Attachments string `json:"attachments"`
}
