// Code generated by godddx, DO AVOID EDIT.
package chat

import "github.com/ixugo/goddd/pkg/web"

type FindSessionInput struct {
	web.PagerFilter
	Title string `form:"title"`
}

type EditSessionInput struct {
	Title string `json:"title"`
}

type AddSessionInput struct {
	Title string `json:"title"`
}
