// Code generated by godddx, DO AVOID EDIT.
package chat

import "time"

// Session domain model
type Session struct {
	ID        string    `gorm:"primaryKey" json:"id"`
	Title     string    `gorm:"column:title;notNull;default:''" json:"title"`
	CreatedAt time.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName database table name
func (*Session) TableName() string {
	return "sessions"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
// 默认应该是 ID 字段，但也可以自定义
func (s *Session) CacheKey() string {
	return s.ID
}
