// Code generated by godddx, DO AVOID EDIT.
package chat

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// SessionStorer Instantiation interface
type SessionStorer interface {
	Find(context.Context, *[]*Session, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Session, ...orm.QueryOption) error
	Add(context.Context, *Session) error
	Edit(context.Context, *Session, func(*Session), ...orm.QueryOption) error
	Del(context.Context, *Session, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	EditWithSession(*gorm.DB, *Session, func(b *Session) error, ...orm.QueryOption) error
}

// FindSession Paginated search
func (c Core) FindSessions(ctx context.Context, in *FindSessionInput) ([]*Session, int64, error) {
	query := orm.NewQuery(1).OrderBy("created_at DESC")

	items := make([]*Session, 0, in.Limit())
	total, err := c.store.Session().Find(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetSession Query a single object
func (c Core) GetSession(ctx context.Context, id string) (*Session, error) {
	// 提前赋值是为了缓存
	out := Session{ID: id}
	if err := c.store.Session().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// AddSession Insert into database
func (c Core) AddSession(ctx context.Context, in *AddSessionInput) (*Session, error) {
	var out Session
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	// TODO: 建议定义前缀
	out.ID = c.uni.UniqueID("")
	if err := c.store.Session().Add(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// EditSession Update object information
func (c Core) EditSession(ctx context.Context, in *EditSessionInput, id string) (*Session, error) {
	var out Session
	if err := c.store.Session().Edit(ctx, &out, func(b *Session) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Edit id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DelSession Delete object
func (c Core) DelSession(ctx context.Context, id string) (*Session, error) {
	var out Session
	if err := c.store.Session().Del(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}
