// Code generated by godddx, DO AVOID EDIT.
package chatdb

import (
	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"gorm.io/gorm"
)

var _ chat.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Session Get business instance
func (d DB) Session() chat.SessionStorer {
	return Session(d)
}

// Message Get business instance
func (d DB) Message() chat.MessageStorer {
	return Message(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(chat.Session),
		new(chat.Message),
	); err != nil {
		panic(err)
	}
	return d
}
