// Code generated by godddx, DO AVOID EDIT.
package chatdb

import (
	"context"

	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ chat.MessageStorer = Message{}

// Message Related business namespaces
type Message DB

// NewMessage instance object
func NewMessage(db *gorm.DB) Message {
	return Message{db: db}
}

// Find implements chat.MessageStorer.
func (d Message) Find(ctx context.Context, bs *[]*chat.Message, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements chat.MessageStorer.
func (d Message) Get(ctx context.Context, model *chat.Message, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements chat.MessageStorer.
func (d Message) Add(ctx context.Context, model *chat.Message) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements chat.MessageStorer.
func (d Message) Edit(ctx context.Context, model *chat.Message, changeFn func(*chat.Message), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements chat.MessageStorer.
func (d Message) Del(ctx context.Context, model *chat.Message, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements chat.MessageStorer.
func (d Message) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[chat.Message](ctx, d.db, opts...)
}

// Session 事务组合
func (d Message) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// EditWithSession 修改事务
func (d Message) EditWithSession(tx *gorm.DB, model *chat.Message, changeFn func(b *chat.Message) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
