// Code generated by godddx, DO AVOID EDIT.
package chatdb

import (
	"context"

	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ chat.SessionStorer = Session{}

// Session Related business namespaces
type Session DB

// NewSession instance object
func NewSession(db *gorm.DB) Session {
	return Session{db: db}
}

// Find implements chat.SessionStorer.
func (d Session) Find(ctx context.Context, bs *[]*chat.Session, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements chat.SessionStorer.
func (d Session) Get(ctx context.Context, model *chat.Session, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements chat.SessionStorer.
func (d Session) Add(ctx context.Context, model *chat.Session) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements chat.SessionStorer.
func (d Session) Edit(ctx context.Context, model *chat.Session, changeFn func(*chat.Session), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements chat.SessionStorer.
func (d Session) Del(ctx context.Context, model *chat.Session, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements chat.SessionStorer.
func (d Session) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[chat.Session](ctx, d.db, opts...)
}

// Session 事务组合
func (d Session) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// EditWithSession 修改事务
func (d Session) EditWithSession(tx *gorm.DB, model *chat.Session, changeFn func(b *chat.Session) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
