// Code generated by godddx, DO AVOID EDIT.
package chatcache

import (
	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/goddd/pkg/conc"
)

var _ chat.Storer = (*Cache)(nil)

func NewCache(store chat.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store:   store,
		session: cache,
		message: cache,
	}
}

type Cache struct {
	store   chat.Storer
	session conc.Cacher
	message conc.Cacher
}

// Session implements chat.SessionStorer
func (c *Cache) Session() chat.SessionStorer {
	return (*Session)(c)
}

// Message implements chat.MessageStorer
func (c *Cache) Message() chat.MessageStorer {
	return (*Message)(c)
}
