// Code generated by godddx, DO AVOID EDIT.
package chatcache

import (
	"context"
	"fmt"

	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ chat.MessageStorer = (*Message)(nil)

type Message Cache

func (c *Message) cacheKey(key any) string {
	return fmt.Sprintf("MESSAGE:%v", key)
}

// Find implements chat.MessageStorer.
func (c *Message) Find(ctx context.Context, bs *[]*chat.Message, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Message().Find(ctx, bs, page, opts...)
}

// Get implements chat.MessageStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Message) Get(ctx context.Context, model *chat.Message, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.message.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Message().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.message.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Add implements chat.MessageStorer.
func (c *Message) Add(ctx context.Context, model *chat.Message) error {
	if err := c.store.Message().Add(ctx, model); err != nil {
		return err
	}
	c.message.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Edit implements chat.MessageStorer.
func (c *Message) Edit(ctx context.Context, model *chat.Message, changeFn func(*chat.Message), opts ...orm.QueryOption) error {
	if err := c.store.Message().Edit(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.message.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements chat.MessageStorer.
func (c *Message) Del(ctx context.Context, model *chat.Message, opts ...orm.QueryOption) error {
	if err := c.store.Message().Del(ctx, model, opts...); err != nil {
		return err
	}
	c.message.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements chat.MessageStorer.
func (c *Message) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Message().Count(ctx, opts...)
}

// Session 事务组合
func (c *Message) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Message().Session(ctx, changeFns...)
	return nil
}

// EditWithSession 修改事务
func (c *Message) EditWithSession(tx *gorm.DB, model *chat.Message, changeFn func(b *chat.Message) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Message().EditWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.message.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
