// Code generated by godddx, DO AVOID EDIT.
package chatcache

import (
	"context"
	"fmt"

	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ chat.SessionStorer = (*Session)(nil)

type Session Cache

func (c *Session) cacheKey(key any) string {
	return fmt.Sprintf("SESSION:%v", key)
}

// Find implements chat.SessionStorer.
func (c *Session) Find(ctx context.Context, bs *[]*chat.Session, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Session().Find(ctx, bs, page, opts...)
}

// Get implements chat.SessionStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Session) Get(ctx context.Context, model *chat.Session, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.session.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Session().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.session.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Add implements chat.SessionStorer.
func (c *Session) Add(ctx context.Context, model *chat.Session) error {
	if err := c.store.Session().Add(ctx, model); err != nil {
		return err
	}
	c.session.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Edit implements chat.SessionStorer.
func (c *Session) Edit(ctx context.Context, model *chat.Session, changeFn func(*chat.Session), opts ...orm.QueryOption) error {
	if err := c.store.Session().Edit(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.session.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements chat.SessionStorer.
func (c *Session) Del(ctx context.Context, model *chat.Session, opts ...orm.QueryOption) error {
	if err := c.store.Session().Del(ctx, model, opts...); err != nil {
		return err
	}
	c.session.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements chat.SessionStorer.
func (c *Session) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Session().Count(ctx, opts...)
}

// Session 事务组合
func (c *Session) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Session().Session(ctx, changeFns...)
	return nil
}

// EditWithSession 修改事务
func (c *Session) EditWithSession(tx *gorm.DB, model *chat.Session, changeFn func(b *chat.Session) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Session().EditWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.session.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
