// Code generated by godddx, DO AVOID EDIT.
package config

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// ConfigStorer Instantiation interface
type ConfigStorer interface {
	Find(context.Context, *[]*Config, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Config, ...orm.QueryOption) error
	Add(context.Context, *Config) error
	Edit(context.Context, *Config, func(*Config), ...orm.QueryOption) error
	Del(context.Context, *Config, ...orm.QueryOption) error
	Count(context.Context, ...orm.QueryOption) (int64, error)

	Session(context.Context, ...func(*gorm.DB) error) error
	EditWithSession(*gorm.DB, *Config, func(b *Config) error, ...orm.QueryOption) error
}

// FindConfig Paginated search
func (c Core) FindConfigs(ctx context.Context, in *FindConfigInput) ([]*Config, int64, error) {
	query := orm.NewQuery(1).OrderBy("created_at DESC")

	items := make([]*Config, 0, in.Limit())
	total, err := c.store.Config().Find(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find in[%+v] err[%s]`, in, err.Error())
	}
	return items, total, nil
}

// GetConfig Query a single object
func (c Core) GetConfig(ctx context.Context, id string) (*Config, error) {
	// 提前赋值是为了缓存
	out := Config{ID: id}
	if err := c.store.Config().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get id[%v] err[%s]`, id, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// AddConfig Insert into database
func (c Core) AddConfig(ctx context.Context, in *AddConfigInput) (*Config, error) {
	var out Config
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	if err := c.store.Config().Add(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Add err[%s]`, err.Error())
	}
	return &out, nil
}

// EditConfig Update object information
func (c Core) EditConfig(ctx context.Context, in *EditConfigInput, id string) (*Config, error) {
	var out Config
	if err := c.store.Config().Edit(ctx, &out, func(b *Config) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Edit id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}

// DelConfig Delete object
func (c Core) DelConfig(ctx context.Context, id string) (*Config, error) {
	var out Config
	if err := c.store.Config().Del(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Del id[%v] err[%s]`, id, err.Error())
	}
	return &out, nil
}
