// Code generated by godddx, DO AVOID EDIT.
package config

import "time"

// Config domain model
type Config struct {
	ID        string    `gorm:"primaryKey" json:"id"`
	Value     string    `gorm:"column:value;notNull;default:''" json:"value"`
	CreatedAt time.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName database table name
func (*Config) TableName() string {
	return "configs"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
// 默认应该是 ID 字段，但也可以自定义
func (c *Config) CacheKey() string {
	return c.ID
}
