// Code generated by godddx, DO AVOID EDIT.
package config

import "github.com/ixugo/goddd/pkg/web"

type FindConfigInput struct {
	web.PagerFilter
	Value string `form:"value"`
}

type EditConfigInput struct {
	Value string `json:"value"`
}

type AddConfigInput struct {
	Value string `json:"value"`
}
