// Code generated by godddx, DO AVOID EDIT.
package config

// Storer data persistence
type Storer interface {
	Config() ConfigStorer
}

// Core business domain
type Core struct {
	store Storer
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{store: store}
}
