// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/ixugo/ffagent/agent/internal/core/chat"
	"github.com/ixugo/ffagent/agent/internal/core/chat/store/chatdb"
	"github.com/ixugo/goddd/domain/uniqueid"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
	"gorm.io/gorm"
)

// ChatAPI 为 http 提供业务方法
type ChatAPI struct {
	chatCore chat.Core
}

func NewChatCore(db *gorm.DB, uni uniqueid.Core) chat.Core {
	var store chat.Storer
	store = chatdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate())
	// 如果需要缓存，可以取消注释
	// store = chatcache.NewCache(store,conc.NewTTLCache(time.Hour))
	return chat.NewCore(store, uni)
}

func NewChatAPI(core chat.Core) ChatAPI {
	return ChatAPI{chatCore: core}
}

// NewChatAPIFromDB 如果已经初始化，可以考虑 NewChatAPI
// func NewChatAPIFromDB(db *gorm.DB) ChatAPI {
// 	return NewChatAPI(NewChatCore(db))
// }

func RegisterChat(g gin.IRouter, api ChatAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/sessions", handler...)
		group.GET("", web.WrapH(api.findSessions))
		group.GET("/:id", web.WrapH(api.getSession))
		group.PUT("/:id", web.WrapH(api.editSession))
		group.POST("", web.WrapH(api.addSession))
		group.DELETE("/:id", web.WrapH(api.delSession))
	}

	{
		group := g.Group("/messages", handler...)
		group.GET("", web.WrapH(api.findMessages))
		group.GET("/:id", web.WrapH(api.getMessage))
		group.PUT("/:id", web.WrapH(api.editMessage))
		group.POST("", web.WrapH(api.addMessage))
		group.DELETE("/:id", web.WrapH(api.delMessage))
	}
}

// >>> session >>>>>>>>>>>>>>>>>>>>

func (a ChatAPI) findSessions(c *gin.Context, in *chat.FindSessionInput) (any, error) {
	items, total, err := a.chatCore.FindSessions(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ChatAPI) getSession(c *gin.Context, _ *struct{}) (*chat.Session, error) {
	sessionID := c.Param("id")
	return a.chatCore.GetSession(c.Request.Context(), sessionID)
}

func (a ChatAPI) editSession(c *gin.Context, in *chat.EditSessionInput) (*chat.Session, error) {
	sessionID := c.Param("id")
	return a.chatCore.EditSession(c.Request.Context(), in, sessionID)
}

func (a ChatAPI) addSession(c *gin.Context, in *chat.AddSessionInput) (*chat.Session, error) {
	return a.chatCore.AddSession(c.Request.Context(), in)
}

func (a ChatAPI) delSession(c *gin.Context, _ *struct{}) (*chat.Session, error) {
	sessionID := c.Param("id")
	return a.chatCore.DelSession(c.Request.Context(), sessionID)
}

// >>> message >>>>>>>>>>>>>>>>>>>>

func (a ChatAPI) findMessages(c *gin.Context, in *chat.FindMessageInput) (any, error) {
	items, total, err := a.chatCore.FindMessages(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ChatAPI) getMessage(c *gin.Context, _ *struct{}) (*chat.Message, error) {
	messageID := c.Param("id")
	return a.chatCore.GetMessage(c.Request.Context(), messageID)
}

func (a ChatAPI) editMessage(c *gin.Context, in *chat.EditMessageInput) (*chat.Message, error) {
	messageID := c.Param("id")
	return a.chatCore.EditMessage(c.Request.Context(), in, messageID)
}

func (a ChatAPI) addMessage(c *gin.Context, in *chat.AddMessageInput) (*chat.Message, error) {
	return a.chatCore.AddMessage(c.Request.Context(), in)
}

func (a ChatAPI) delMessage(c *gin.Context, _ *struct{}) (*chat.Message, error) {
	messageID := c.Param("id")
	return a.chatCore.DelMessage(c.Request.Context(), messageID)
}
