// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/ixugo/ffagent/agent/internal/core/config"
	"github.com/ixugo/ffagent/agent/internal/core/config/store/configdb"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
	"gorm.io/gorm"
)

// ConfigAPI 为 http 提供业务方法
type ConfigAPI struct {
	configCore config.Core
}

func NewConfigCore(db *gorm.DB) config.Core {
	var store config.Storer
	store = configdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate())
	// 如果需要缓存，可以取消注释
	// store = configcache.NewCache(store,conc.NewTTLCache(time.Hour))
	return config.NewCore(store)
}

func NewConfigAPI(core config.Core) ConfigAPI {
	return ConfigAPI{configCore: core}
}

// NewConfigAPIFromDB 如果已经初始化，可以考虑 NewConfigAPI
// func NewConfigAPIFromDB(db *gorm.DB) ConfigAPI {
// 	return NewConfigAPI(NewConfigCore(db))
// }

func RegisterConfig(g gin.IRouter, api ConfigAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/configs", handler...)
		group.GET("", web.WrapH(api.findConfigs))
		group.GET("/:id", web.WrapH(api.getConfig))
		group.PUT("/:id", web.WrapH(api.editConfig))
		group.POST("", web.WrapH(api.addConfig))
		group.DELETE("/:id", web.WrapH(api.delConfig))
	}
}

// >>> config >>>>>>>>>>>>>>>>>>>>

func (a ConfigAPI) findConfigs(c *gin.Context, in *config.FindConfigInput) (any, error) {
	items, total, err := a.configCore.FindConfigs(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ConfigAPI) getConfig(c *gin.Context, _ *struct{}) (*config.Config, error) {
	configID := c.Param("id")
	return a.configCore.GetConfig(c.Request.Context(), configID)
}

func (a ConfigAPI) editConfig(c *gin.Context, in *config.EditConfigInput) (*config.Config, error) {
	configID := c.Param("id")
	return a.configCore.EditConfig(c.Request.Context(), in, configID)
}

func (a ConfigAPI) addConfig(c *gin.Context, in *config.AddConfigInput) (*config.Config, error) {
	return a.configCore.AddConfig(c.Request.Context(), in)
}

func (a ConfigAPI) delConfig(c *gin.Context, _ *struct{}) (*config.Config, error) {
	configID := c.Param("id")
	return a.configCore.DelConfig(c.Request.Context(), configID)
}
