// Code generated by godddx, DO AVOID EDIT.
package metadata

// Storer data persistence
type Storer interface {
	Metadata() MetadataStorer
}

// Core business domain
type Core struct {
	store Storer
}

// NewCore create business domain
func NewCore(store Storer) Core {
	return Core{store: store}
}
