// Code generated by godddx, DO AVOID EDIT.
package metadata

// FindMetadataInput 查询数据参数（保留未使用）
// type FindMetadataInput struct {
// 	web.PagerFilter
// }

// AddMetadataInput 新增数据参数
type AddMetadataInput struct {
	ID  string `json:"id" binding:"required,max=12"`    // 调用方指定的唯一标识
	Ext string `json:"ext" binding:"required,max=2048"` // 序列化的 JSON 字符串

	CreatedBy     string `json:"-"` // 创建者（API层填充）
	LastUpdatedBy string `json:"-"` // 最后更新者（API层填充）
}

// EditMetadataInput 编辑数据参数
type EditMetadataInput struct {
	Ext string `json:"ext" binding:"required,max=2048"` // 序列化的 JSON 字符串

	LastUpdatedBy string `json:"-"` // 最后更新者（API层填充）
}

// SaveMetadataInput 保存数据参数，合并创建与更新为一个幂等操作
type SaveMetadataInput struct {
	Ext string `json:"ext" binding:"required,max=2048"` // 序列化的 JSON 字符串

	CreatedBy     string `json:"-"` // 创建者（API层填充）
	LastUpdatedBy string `json:"-"` // 最后更新者（API层填充）
}
