// Code generated by godddx, DO AVOID EDIT.
package metadatadb

import (
	"github.com/ixugo/ffagent/agent/internal/core/metadata"
	"gorm.io/gorm"
)

var _ metadata.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Metadata Get business instance
func (d DB) Metadata() metadata.MetadataStorer {
	return Metadata(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(metadata.Metadata),
	); err != nil {
		panic(err)
	}
	return d
}
