// Code generated by godddx, DO AVOID EDIT.
package metadatadb

import (
	"context"

	"github.com/ixugo/ffagent/agent/internal/core/metadata"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ metadata.MetadataStorer = Metadata{}

// Metadata Related business namespaces
type Metadata DB

// NewMetadata instance object
func NewMetadata(db *gorm.DB) Metadata {
	return Metadata{db: db}
}

// Find implements metadata.MetadataStorer.
func (d Metadata) Find(ctx context.Context, bs *[]*metadata.Metadata, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements metadata.MetadataStorer.
func (d Metadata) Get(ctx context.Context, model *metadata.Metadata, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements metadata.MetadataStorer.
func (d Metadata) Add(ctx context.Context, model *metadata.Metadata) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements metadata.MetadataStorer.
func (d Metadata) Edit(ctx context.Context, model *metadata.Metadata, changeFn func(*metadata.Metadata), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements metadata.MetadataStorer.
func (d Metadata) Del(ctx context.Context, model *metadata.Metadata, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements metadata.MetadataStorer.
func (d Metadata) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[metadata.Metadata](ctx, d.db, opts...)
}

// Session 事务组合
func (d Metadata) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// EditWithSession 修改事务
func (d Metadata) EditWithSession(tx *gorm.DB, model *metadata.Metadata, changeFn func(b *metadata.Metadata) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
