// Code generated by godddx, DO AVOID EDIT.
package configcache

import (
	"github.com/ixugo/ffagent/agent/internal/core/config"
	"github.com/ixugo/goddd/pkg/conc"
)

var _ config.Storer = (*Cache)(nil)

func NewCache(store config.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store:  store,
		config: cache,
	}
}

type Cache struct {
	store  config.Storer
	config conc.Cacher
}

// Config implements config.ConfigStorer
func (c *Cache) Config() config.ConfigStorer {
	return (*Config)(c)
}
