// Code generated by godddx, DO AVOID EDIT.
package configcache

import (
	"context"
	"fmt"

	"github.com/ixugo/ffagent/agent/internal/core/config"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ config.ConfigStorer = (*Config)(nil)

type Config Cache

func (c *Config) cacheKey(key any) string {
	return fmt.Sprintf("CONFIG:%v", key)
}

// Find implements config.ConfigStorer.
func (c *Config) Find(ctx context.Context, bs *[]*config.Config, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Config().Find(ctx, bs, page, opts...)
}

// Get implements config.ConfigStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Config) Get(ctx context.Context, model *config.Config, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.config.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Config().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.config.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Add implements config.ConfigStorer.
func (c *Config) Add(ctx context.Context, model *config.Config) error {
	if err := c.store.Config().Add(ctx, model); err != nil {
		return err
	}
	c.config.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Edit implements config.ConfigStorer.
func (c *Config) Edit(ctx context.Context, model *config.Config, changeFn func(*config.Config), opts ...orm.QueryOption) error {
	if err := c.store.Config().Edit(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.config.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Del implements config.ConfigStorer.
func (c *Config) Del(ctx context.Context, model *config.Config, opts ...orm.QueryOption) error {
	if err := c.store.Config().Del(ctx, model, opts...); err != nil {
		return err
	}
	c.config.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements config.ConfigStorer.
func (c *Config) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Config().Count(ctx, opts...)
}

// Session 事务组合
func (c *Config) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Config().Session(ctx, changeFns...)
	return nil
}

// EditWithSession 修改事务
func (c *Config) EditWithSession(tx *gorm.DB, model *config.Config, changeFn func(b *config.Config) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Config().EditWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.config.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
